"""message

Revision ID: 4e8ef6496854
Revises: 17de9398142e
Create Date: 2025-07-09 16:22:54.372605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e8ef6496854'
down_revision: Union[str, None] = '17de9398142e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name_uz', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('name_ru', sa.String(), nullable=False))
    op.add_column('categories', sa.Column('name_en', sa.String(), nullable=False))
    op.drop_column('categories', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('name', sa.VARCHAR(), nullable=False))
    op.drop_column('categories', 'name_en')
    op.drop_column('categories', 'name_ru')
    op.drop_column('categories', 'name_uz')
    # ### end Alembic commands ###
