"""fixed products table

Revision ID: 6b7d1eb8c8f4
Revises: 799c74e728a0
Create Date: 2025-07-12 22:55:45.468479

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b7d1eb8c8f4'
down_revision: Union[str, None] = '799c74e728a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_uz', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name_en', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('name_ru', sa.String(), nullable=False))
        batch_op.drop_column('name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('name_ru')
        batch_op.drop_column('name_en')
        batch_op.drop_column('name_uz')

    # ### end Alembic commands ###
